# Generated by Django 3.0.2 on 2020-01-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcontact',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='newcontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='newcontact',
            name='current_website',
        ),
    ]
